# Generated by Django 4.1.2 on 2022-10-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="column",
            old_name="data",
            new_name="info",
        ),
        migrations.RenameField(
            model_name="value",
            old_name="data",
            new_name="info",
        ),
    ]
