# Generated by Django 4.1.2 on 2022-10-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_rename_data_column_info_rename_data_value_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="value",
            name="row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="db.row",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="value",
            unique_together={("column", "row")},
        ),
    ]
